// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypvvzqsofqtoikwnsuyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdnZ6cXNvZnF0b2lrd25zdXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzUxOTcsImV4cCI6MjA2MTc1MTE5N30.WzwJ0MF6UFExSP1OEUEhEPLUrketmRcqHQokywlO47Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);